name: SABBIR MODZ SHOP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        run: python bot.py
